const product= [
    {
        isHotSell:false,
        productName:"Waterproof High End Led Screen For Activity",
        productModel:"waterproof-high-end-led-screen-for-activity",
        brand:"TENTECH",
        productOrigin:"CHINA",
        supplyCapacity:"100 SQM PER DAY",
        deliveryTime:"3-5DAYS",
        description:[
            {title:"",value:"Special Design This Panel has both 500*500mm and 500*1000mm verstion,and the two verstion can be used togother.Has achieve Front and rear maintenance.Rental Stage Indoor LED Screen 3.91 Video Full Color Led Panel Display/Screen LED Panel"},
            {title:"",value:"Exquisite Craft The curve lock it adopts is very easy to operate,both concave and convex is available,the manufacturing is precise amd accurate"},
            {title:"Excellent Quality",value:"Our field-tested LED panel is a self-contained, modular unit made of die-casting aluminum to provide superior heat dissipation,durability, and a longer lifespan. Unlike most digital signs, ours have no fans. This unique product meets strict quality controland is backed by a three year warranty."},
        ],
        specsType:1,
        productSpecs: [
            {
                title:"",
                specs:[
                    { title: "Application", content: "Indoor" },
                    { title: "Color", content: "Full Color" },
                    { title: "Panel Size", content: "500*500mm" },
                    { title: "Pixel Pitch", content: "1.9/2.6/2.9/3.91/4.81mm" },
                    { title: "Place of Origin", content: "Guangdong, China" },
                    { title: "Model Number", content: "E3.9" },
                    { title: "Brand Name", content: "Tentech" },
                    { title: "Product Name", content: "P 3.91 Smd P2.976 P391 4.81 1.9Mm Smd2121 Display Wall" },
                    { title: "Cabinet size", content: "500*500*64mm" },
                    { title: "Cabinet weight", content: "6Kgs" },
                    { title: "Cabinet pixels (dots)", content: "128*128" },
                    { title: "Refresh Rate(Hz)", content: "≥1920" },
                    { title: "Driving Method", content: "1/16" },
                    { title: "Cabinet Material", content: "Die Casting Alunimum" },
                    { title: "Brightness", content: "1200nits" },
                    { title: "LED Chips", content: "SMD2121" }
                ]
            },
            {
                title: "",
                specs:  [
                    { title: "Model Number", content: "P3.91-13S" },
                    { title: "Module size", content: "250mm*250mm" },
                    { title: "Pixel pitch", content: "3.91mm" },
                    { title: "Pixels Density", content: "65536/m2" },
                    { title: "Pixel configuration", content: "1R1G1B" },
                    { title: "Package mode", content: "SMD1921" },
                    { title: "Pixel resolution", content: "64dots(W)*64dots(H)" },
                    { title: "Max Power consumption", content: "60W" },
                    { title: "Weight", content: "1.2kg" },
                    { title: "Drive type", content: "Constant drive" },
                    { title: "Scan mode", content: "1/16scan" },
                    { title: "LED Unit Module", content: "" },
                    { title: "Quanty of Module", content: "4pcs/8pcs" },
                    { title: "Power supply", content: "5V/60A" },
                    { title: "Pixel per cabinet", content: "128*128/128*256" },
                    { title: "Brightness of white balance", content: "≥7500cd/m2" },
                    { title: "Best viewing distance", content: "4M~50M" },
                    { title: "Viewing angles", content: "160°(W) 120°(H)" },
                    { title: "Temperature storage", content: "-35℃~+85℃, working:-20℃~+50℃" },
                    { title: "Operation humidity", content: "10%-95%" },
                    { title: "Thickness", content: "85mm" },
                    { title: "Power Working voltage", content: "AC220V±10%" },
                    { title: "Average Power consumption", content: "600W/S" },
                    { title: "Max.Power consumption", content: "≤1800W/S" },
                    { title: "Current", content: "≤20mA(single LED)" },
                    { title: "Control system CPU", content: "Pentium 4 or above" },
                    { title: "Operation system", content: "WIN98/2000/NT/XP" },
                    { title: "Control method", content: "Synchronization" },
                    { title: "Main technical parameter", content: "" },
                    { title: "Driving device", content: "Constant currentdriver IC Refresh frequency: ≥400HZ" },
                    { title: "Grey scale/colors", content: "RGB256,16.7M 256levels of each color(RGB)/16.7M colors" },
                    { title: "MTBF", content: "≥9000hours" },
                    { title: "Power switch", content: "Automatic switch" },
                    { title: "Display Mode", content: "800*600/1024*768" },
                    { title: "Waterproof Rate", content: "IP65" }
                ],
            },
        ],
        warrentyTerms:{
            title:"Tentech provides an excellent after-sales service on the prerequisite of customer satisfaction.",
            terms:[
                {termsContent:"All the products owners purchased from TENTECH possess the following rights:",subTermsContent:[
                        {title:"A:Unconditional replacement within 7 days."},
                        {title:"B:2 years warranty for maintenance."},
                    ]},
                {termsContent:"The repaired products will be sent back at TENTECH cost to customer within 7 days( from the date we receive the defective products at customers cost).",subTermsContent:[]},
                {termsContent:"100% authentic strict assessment, for you to select high visibility, quality, good service goods; 10 times refund in case any fake were found.",subTermsContent:[]},
                {termsContent:"12 hours after-sale service TENTECH professional services team promises to resolve any problems related to the use, installation and configuration of the product within 12 hours.",subTermsContent:[]},
                {termsContent:" 30 days price protection If the price of the products as what you purchased is getting lower within 30 days, TENTECH will refund the price difference. ",subTermsContent:[]},
            ]
        },
        productBrochure:{title:"Product Brochure",downloadUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/waterproof-high-end-led-screen-for-activity/waterproof-high-end-led-screen-for-activity.pdf"},
        productMediaResources:[
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/waterproof-high-end-led-screen-for-activity/waterproof-high-end-led-screen-for-activity-01.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/waterproof-high-end-led-screen-for-activity/waterproof-high-end-led-screen-for-activity-02.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/waterproof-high-end-led-screen-for-activity/waterproof-high-end-led-screen-for-activity-03.jpg"},
        ],
        productTag:[
            {tagTitle:"waterproof led screen",value:"waterproof+led+screen"},
            {tagTitle:"P3.91 Outdoor LED Screen for advertising and rental",value:"P391+Outdoor+LED+Screen+for+advertising+and+rental"},
            {tagTitle:"P3.91 Rental Outdoor Led Display",value:"P391+Rental+Outdoor+Led+Display"},
            {tagTitle:"Waterproof Giant P3 Stage Led Video Wall Panel Screen",value:"Waterproof+Giant+P3+Stage+Led+Video+Wall+Panel+Screen"},
        ]
    },
    {
        isHotSell:false,
        productName:"3.91mm 4.81 Mm 500*1000mm Rental Screen",
        productModel:"391mm-481-mm-5001000mm-rental-screen",
        brand:"TENTECH",
        productOrigin:"CHINA",
        supplyCapacity:"100 SQM PER DAY",
        deliveryTime:"3-5DAYS",
        description:[
            {title:"",value:"Special Design This Panel has both 500*500mm and 500*1000mm verstion,and the two verstion can be used togother.Has achieve Front and rear maintenance.Rental Stage Indoor LED Screen 3.91 Video Full Color Led Panel Display/Screen LED Panel"},
            {title:"",value:"Exquisite Craft The curve lock it adopts is very easy to operate,both concave and convex is available,the manufacturing is precise amd accurate"},
            {title:"Excellent Quality",value:"Our field-tested LED panel is a self-contained, modular unit made of die-casting aluminum to provide superior heat dissipation,durability, and a longer lifespan. Unlike most digital signs, ours have no fans. This unique product meets strict quality controland is backed by a three year warranty."},
        ],
        specsType:1,
        productSpecs: [
            {
                title:"",
                specs:[
                    { title: "Application", content: "Indoor" },
                    { title: "Color", content: "Full Color" },
                    { title: "Panel Size", content: "500*500mm" },
                    { title: "Pixel Pitch", content: "1.9/2.6/2.9/3.91/4.81mm" },
                    { title: "Place of Origin", content: "Guangdong, China" },
                    { title: "Model Number", content: "E3.9" },
                    { title: "Brand Name", content: "Tentech" },
                    { title: "Product Name", content: "P 3.91 Smd P2.976 P391 4.81 1.9Mm Smd2121 Display Wall" },
                    { title: "Cabinet size", content: "500*500*64mm" },
                    { title: "Cabinet weight", content: "6Kgs" },
                    { title: "Cabinet pixels (dots)", content: "128*128" },
                    { title: "Refresh Rate(Hz)", content: "≥1920" },
                    { title: "Driving Method", content: "1/16" },
                    { title: "Cabinet Material", content: "Die Casting Alunimum" },
                    { title: "Brightness", content: "1200nits" },
                    { title: "LED Chips", content: "SMD2121" }
                ]
            },
            {
                title: "",
                specs:  [
                    { title: "Model Number", content: "P3.91-13S" },
                    { title: "Module size", content: "250mm*250mm" },
                    { title: "Pixel pitch", content: "3.91mm" },
                    { title: "Pixels Density", content: "65536/m2" },
                    { title: "Pixel configuration", content: "1R1G1B" },
                    { title: "Package mode", content: "SMD1921" },
                    { title: "Pixel resolution", content: "64dots(W)*64dots(H)" },
                    { title: "Max Power consumption", content: "60W" },
                    { title: "Weight", content: "1.2kg" },
                    { title: "Drive type", content: "Constant drive" },
                    { title: "Scan mode", content: "1/16scan" },
                    { title: "LED Unit Module", content: "" },
                    { title: "Quanty of Module", content: "4pcs/8pcs" },
                    { title: "Power supply", content: "5V/60A" },
                    { title: "Pixel per cabinet", content: "128*128/128*256" },
                    { title: "Brightness of white balance", content: "≥7500cd/m2" },
                    { title: "Best viewing distance", content: "4M~50M" },
                    { title: "Viewing angles", content: "160°(W) 120°(H)" },
                    { title: "Temperature storage", content: "-35℃~+85℃, working:-20℃~+50℃" },
                    { title: "Operation humidity", content: "10%-95%" },
                    { title: "Thickness", content: "85mm" },
                    { title: "Power Working voltage", content: "AC220V±10%" },
                    { title: "Average Power consumption", content: "600W/S" },
                    { title: "Max.Power consumption", content: "≤1800W/S" },
                    { title: "Current", content: "≤20mA(single LED)" },
                    { title: "Control system CPU", content: "Pentium 4 or above" },
                    { title: "Operation system", content: "WIN98/2000/NT/XP" },
                    { title: "Control method", content: "Synchronization" },
                    { title: "Main technical parameter", content: "" },
                    { title: "Driving device", content: "Constant currentdriver IC Refresh frequency: ≥400HZ" },
                    { title: "Grey scale/colors", content: "RGB256,16.7M 256levels of each color(RGB)/16.7M colors" },
                    { title: "MTBF", content: "≥9000hours" },
                    { title: "Power switch", content: "Automatic switch" },
                    { title: "Display Mode", content: "800*600/1024*768" },
                    { title: "Waterproof Rate", content: "IP65" }
                ],
            },
        ],
        warrentyTerms:{
            title:"Tentech provides an excellent after-sales service on the prerequisite of customer satisfaction.",
            terms:[
                {termsContent:"All the products owners purchased from TENTECH possess the following rights:",subTermsContent:[
                        {title:"A:Unconditional replacement within 7 days."},
                        {title:"B:2 years warranty for maintenance."},
                    ]},
                {termsContent:"The repaired products will be sent back at TENTECH cost to customer within 7 days( from the date we receive the defective products at customers cost).",subTermsContent:[]},
                {termsContent:"100% authentic strict assessment, for you to select high visibility, quality, good service goods; 10 times refund in case any fake were found.",subTermsContent:[]},
                {termsContent:"12 hours after-sale service TENTECH professional services team promises to resolve any problems related to the use, installation and configuration of the product within 12 hours.",subTermsContent:[]},
                {termsContent:" 30 days price protection If the price of the products as what you purchased is getting lower within 30 days, TENTECH will refund the price difference. ",subTermsContent:[]},
            ]
        },
        productBrochure:{title:"Product Brochure",downloadUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/391mm-481-mm-5001000mm-rental-screen/391mm-481-mm-5001000mm-rental-screen.pdf"},
        productMediaResources:[
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/391mm-481-mm-5001000mm-rental-screen/391mm-481-mm-5001000mm-rental-screen-01.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/391mm-481-mm-5001000mm-rental-screen/391mm-481-mm-5001000mm-rental-screen-02.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/391mm-481-mm-5001000mm-rental-screen/391mm-481-mm-5001000mm-rental-screen-03.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/391mm-481-mm-5001000mm-rental-screen/391mm-481-mm-5001000mm-rental-screen-04.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/391mm-481-mm-5001000mm-rental-screen/391mm-481-mm-5001000mm-rental-screen-05.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/391mm-481-mm-5001000mm-rental-screen/391mm-481-mm-5001000mm-rental-screen-06.jpg"},
        ],
        productTag:[
            {tagTitle:"500*1000mm rental screen",value:"500%2A1000mm+rental+screen"},
            {tagTitle:"Led video wall P3.91 P4.81 rental led display screen for wedding stage",value:"Led+video+wall+P391+P481+rental+led+display+screen+for+wedding+stage"},
            {tagTitle:"1000*500 P3.91 outdoor indoor rental led display screen billboard",value:"1000%2A500+P391+outdoor+indoor+rental+led+display+screen+billboard"},
            {tagTitle:"Outdoor Led Display Panels Screen",value:"Outdoor+Led+Display+Panels+Screen"},
            {tagTitle:"TV Video Wall Rental Display Billboards",value:"TV+Video+Wall+Rental+Display+Billboards"},
        ]
    },
    {
        isHotSell:false,
        productName:"500*500mm Cabinet Rental Screen 32scan",
        productModel:"500500mm-cabinet-rental-screen-32scan",
        brand:"TENTECH",
        productOrigin:"CHINA",
        supplyCapacity:"100 SQM PER DAY",
        deliveryTime:"3-5DAYS",
        description:[
            {title:"",value:"Special Design This Panel has both 500*500mm and 500*1000mm verstion,and the two verstion can be used togother.Has achieve Front and rear maintenance.Rental Stage Indoor LED Screen 3.91 Video Full Color Led Panel Display/Screen LED Panel"},
            {title:"",value:"Exquisite Craft The curve lock it adopts is very easy to operate,both concave and convex is available,the manufacturing is precise amd accurate"},
            {title:"Excellent Quality",value:"Our field-tested LED panel is a self-contained, modular unit made of die-casting aluminum to provide superior heat dissipation,durability, and a longer lifespan. Unlike most digital signs, ours have no fans. This unique product meets strict quality controland is backed by a three year warranty."},
        ],
        specsType:1,
        productSpecs: [
            {
                title:"",
                specs:[
                    { title: "Application", content: "Indoor" },
                    { title: "Color", content: "Full Color" },
                    { title: "Panel Size", content: "500*500mm" },
                    { title: "Pixel Pitch", content: "1.9/2.6/2.9/3.91/4.81mm" },
                    { title: "Place of Origin", content: "Guangdong, China" },
                    { title: "Model Number", content: "E3.9" },
                    { title: "Brand Name", content: "Tentech" },
                    { title: "Product Name", content: "P 3.91 Smd P2.976 P391 4.81 1.9Mm Smd2121 Display Wall" },
                    { title: "Cabinet size", content: "500*500*64mm" },
                    { title: "Cabinet weight", content: "6Kgs" },
                    { title: "Cabinet pixels (dots)", content: "128*128" },
                    { title: "Refresh Rate(Hz)", content: "≥1920" },
                    { title: "Driving Method", content: "1/16" },
                    { title: "Cabinet Material", content: "Die Casting Alunimum" },
                    { title: "Brightness", content: "1200nits" },
                    { title: "LED Chips", content: "SMD2121" }
                ]
            },
            {
                title: "OUTDOOR Item Parameter",
                specs:  [
                    { title: "Model Number", content: "P3.91-13S" },
                    { title: "Module size", content: "250mm*250mm" },
                    { title: "Pixel pitch", content: "3.91mm" },
                    { title: "Pixels Density", content: "65536/m2" },
                    { title: "Pixel configuration", content: "1R1G1B" },
                    { title: "Package mode", content: "SMD1921" },
                    { title: "Pixel resolution", content: "64dots(W)*64dots(H)" },
                    { title: "Max Power consumption", content: "60W" },
                    { title: "Weight", content: "1.2kg" },
                    { title: "Drive type", content: "Constant drive" },
                    { title: "Scan mode", content: "1/16scan" },
                    { title: "LED Unit Module", content: "" },
                    { title: "Quanty of Module", content: "4pcs/8pcs" },
                    { title: "Power supply", content: "5V/60A" },
                    { title: "Pixel per cabinet", content: "128*128/128*256" },
                    { title: "Brightness of white balance", content: "≥7500cd/m2" },
                    { title: "Best viewing distance", content: "4M~50M" },
                    { title: "Viewing angles", content: "160°(W) 120°(H)" },
                    { title: "Temperature storage", content: "-35℃~+85℃, working:-20℃~+50℃" },
                    { title: "Operation humidity", content: "10%-95%" },
                    { title: "Thickness", content: "85mm" },
                    { title: "Power Working voltage", content: "AC220V±10%" },
                    { title: "Average Power consumption", content: "600W/S" },
                    { title: "Max.Power consumption", content: "≤1800W/S" },
                    { title: "Current", content: "≤20mA(single LED)" },
                    { title: "Control system CPU", content: "Pentium 4 or above" },
                    { title: "Operation system", content: "WIN98/2000/NT/XP" },
                    { title: "Control method", content: "Synchronization" },
                    { title: "Main technical parameter", content: "" },
                    { title: "Driving device", content: "Constant currentdriver IC Refresh frequency: ≥400HZ" },
                    { title: "Grey scale/colors", content: "RGB256,16.7M 256levels of each color(RGB)/16.7M colors" },
                    { title: "MTBF", content: "≥9000hours" },
                    { title: "Power switch", content: "Automatic switch" },
                    { title: "Display Mode", content: "800*600/1024*768" },
                    { title: "Waterproof Rate", content: "IP65" }
                ],
            },
        ],
        warrentyTerms:{
            title:"Tentech provides an excellent after-sales service on the prerequisite of customer satisfaction.",
            terms:[
                {termsContent:"All the products owners purchased from TENTECH possess the following rights:",subTermsContent:[
                        {title:"A:Unconditional replacement within 7 days."},
                        {title:"B:2 years warranty for maintenance."},
                    ]},
                {termsContent:"The repaired products will be sent back at TENTECH cost to customer within 7 days( from the date we receive the defective products at customers cost).",subTermsContent:[]},
                {termsContent:"100% authentic strict assessment, for you to select high visibility, quality, good service goods; 10 times refund in case any fake were found.",subTermsContent:[]},
                {termsContent:"12 hours after-sale service TENTECH professional services team promises to resolve any problems related to the use, installation and configuration of the product within 12 hours.",subTermsContent:[]},
                {termsContent:" 30 days price protection If the price of the products as what you purchased is getting lower within 30 days, TENTECH will refund the price difference. ",subTermsContent:[]},
            ]
        },
        productBrochure:{title:"Product Brochure",downloadUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/500500mm-cabinet-rental-screen-32scan/500500mm-cabinet-rental-screen-32scan.pdf"},
        productMediaResources:[
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/500500mm-cabinet-rental-screen-32scan/500500mm-cabinet-rental-screen-32scan-01.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/500500mm-cabinet-rental-screen-32scan/500500mm-cabinet-rental-screen-32scan-02.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/500500mm-cabinet-rental-screen-32scan/500500mm-cabinet-rental-screen-32scan-03.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/500500mm-cabinet-rental-screen-32scan/500500mm-cabinet-rental-screen-32scan-04.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/500500mm-cabinet-rental-screen-32scan/500500mm-cabinet-rental-screen-32scan-05.jpg"},
        ],
        productTag:[
            {tagTitle:"500*500mm rental screen",value:"500%2A500mm+rental+screen"},
            {tagTitle:"Chinese LED display manufacturer rental led screen p391",value:"Chinese+LED+display+manufacturer+rental+led+screen+p391"},
            {tagTitle:"2021 new HD full color P391 Rental indoor 500 X 500 Led Display",value:"2021+new+HD+full+color+P391+Rental+indoor+500+X+500+Led+Display"},
        ]
    },
    {
        isHotSell:false,
        productName:"Indoor 4.81 Mm Led Display Big Wall",
        productModel:"indoor-481-mm-led-display-big-wall",
        brand:"TENTECH",
        productOrigin:"CHINA",
        supplyCapacity:"100 SQM PER DAY",
        deliveryTime:"3-5DAYS",
        description:[
            {title:"",value:"Special Design This Panel has both 500*500mm and 500*1000mm verstion,and the two verstion can be used togother.Has achieve Front and rear maintenance.Rental Stage Indoor LED Screen 3.91 Video Full Color Led Panel Display/Screen LED Panel"},
            {title:"",value:"Exquisite Craft The curve lock it adopts is very easy to operate,both concave and convex is available,the manufacturing is precise amd accurate"},
            {title:"Excellent Quality",value:"Our field-tested LED panel is a self-contained, modular unit made of die-casting aluminum to provide superior heat dissipation,durability, and a longer lifespan. Unlike most digital signs, ours have no fans. This unique product meets strict quality controland is backed by a three year warranty."},
        ],
        specsType:1,
        productSpecs: [
            {
                title:"",
                specs:[
                    { title: "Application", content: "Indoor" },
                    { title: "Color", content: "Full Color" },
                    { title: "Panel Size", content: "500*500mm" },
                    { title: "Pixel Pitch", content: "1.9/2.6/2.9/3.91/4.81mm" },
                    { title: "Place of Origin", content: "Guangdong, China" },
                    { title: "Model Number", content: "E3.9" },
                    { title: "Brand Name", content: "Tentech" },
                    { title: "Product Name", content: "P 3.91 Smd P2.976 P391 4.81 1.9Mm Smd2121 Display Wall" },
                    { title: "Cabinet size", content: "500*500*64mm" },
                    { title: "Cabinet weight", content: "6Kgs" },
                    { title: "Cabinet pixels (dots)", content: "128*128" },
                    { title: "Refresh Rate(Hz)", content: "≥1920" },
                    { title: "Driving Method", content: "1/16" },
                    { title: "Cabinet Material", content: "Die Casting Alunimum" },
                    { title: "Brightness", content: "1200nits" },
                    { title: "LED Chips", content: "SMD2121" }
                ]
            },
            {
                title: "OUTDOOR Item Parameter",
                specs:  [
                    { title: "Model Number", content: "P3.91-13S" },
                    { title: "Module size", content: "250mm*250mm" },
                    { title: "Pixel pitch", content: "3.91mm" },
                    { title: "Pixels Density", content: "65536/m2" },
                    { title: "Pixel configuration", content: "1R1G1B" },
                    { title: "Package mode", content: "SMD1921" },
                    { title: "Pixel resolution", content: "64dots(W)*64dots(H)" },
                    { title: "Max Power consumption", content: "60W" },
                    { title: "Weight", content: "1.2kg" },
                    { title: "Drive type", content: "Constant drive" },
                    { title: "Scan mode", content: "1/16scan" },
                    { title: "LED Unit Module", content: "" },
                    { title: "Quanty of Module", content: "4pcs/8pcs" },
                    { title: "Power supply", content: "5V/60A" },
                    { title: "Pixel per cabinet", content: "128*128/128*256" },
                    { title: "Brightness of white balance", content: "≥7500cd/m2" },
                    { title: "Best viewing distance", content: "4M~50M" },
                    { title: "Viewing angles", content: "160°(W) 120°(H)" },
                    { title: "Temperature storage", content: "-35℃~+85℃, working:-20℃~+50℃" },
                    { title: "Operation humidity", content: "10%-95%" },
                    { title: "Thickness", content: "85mm" },
                    { title: "Power Working voltage", content: "AC220V±10%" },
                    { title: "Average Power consumption", content: "600W/S" },
                    { title: "Max.Power consumption", content: "≤1800W/S" },
                    { title: "Current", content: "≤20mA(single LED)" },
                    { title: "Control system CPU", content: "Pentium 4 or above" },
                    { title: "Operation system", content: "WIN98/2000/NT/XP" },
                    { title: "Control method", content: "Synchronization" },
                    { title: "Main technical parameter", content: "" },
                    { title: "Driving device", content: "Constant currentdriver IC Refresh frequency: ≥400HZ" },
                    { title: "Grey scale/colors", content: "RGB256,16.7M 256levels of each color(RGB)/16.7M colors" },
                    { title: "MTBF", content: "≥9000hours" },
                    { title: "Power switch", content: "Automatic switch" },
                    { title: "Display Mode", content: "800*600/1024*768" },
                    { title: "Waterproof Rate", content: "IP65" }
                ],
            },
        ],
        warrentyTerms:{
            title:"Tentech provides an excellent after-sales service on the prerequisite of customer satisfaction.",
            terms:[
                {termsContent:"All the products owners purchased from TENTECH possess the following rights:",subTermsContent:[
                        {title:"A:Unconditional replacement within 7 days."},
                        {title:"B:2 years warranty for maintenance."},
                    ]},
                {termsContent:"The repaired products will be sent back at TENTECH cost to customer within 7 days( from the date we receive the defective products at customers cost).",subTermsContent:[]},
                {termsContent:"100% authentic strict assessment, for you to select high visibility, quality, good service goods; 10 times refund in case any fake were found.",subTermsContent:[]},
                {termsContent:"12 hours after-sale service TENTECH professional services team promises to resolve any problems related to the use, installation and configuration of the product within 12 hours.",subTermsContent:[]},
                {termsContent:" 30 days price protection If the price of the products as what you purchased is getting lower within 30 days, TENTECH will refund the price difference. ",subTermsContent:[]},
            ]
        },
        productBrochure:{title:"Product Brochure",downloadUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/indoor-481-mm-led-display-big-wall/indoor-481-mm-led-display-big-wall.pdf"},
        productMediaResources:[
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/indoor-481-mm-led-display-big-wall/indoor-481-mm-led-display-big-wall-01.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/indoor-481-mm-led-display-big-wall/indoor-481-mm-led-display-big-wall-02.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/indoor-481-mm-led-display-big-wall/indoor-481-mm-led-display-big-wall-03.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/indoor-481-mm-led-display-big-wall/indoor-481-mm-led-display-big-wall-04.jpg"},

        ],
        productTag:[
            {tagTitle:"500*500mm rental screen",value:"500%2A500mm+rental+screen"},
            {tagTitle:"Chinese LED display manufacturer rental led screen p391",value:"Chinese+LED+display+manufacturer+rental+led+screen+p391"},
            {tagTitle:"2021 new HD full color P391 Rental indoor 500 X 500 Led Display",value:"2021+new+HD+full+color+P391+Rental+indoor+500+X+500+Led+Display"},
        ]
    },
    {
        isHotSell:false,
        productName:"Outdoor Waterproof 3.91 Led Display",
        productModel:"outdoor-waterproof-391-led-display",
        brand:"TENTECH",
        productOrigin:"CHINA",
        supplyCapacity:"100 SQM PER DAY",
        deliveryTime:"3-5DAYS",
        description:[
            {title:"",value:"Special Design This Panel has both 500*500mm and 500*1000mm verstion,and the two verstion can be used togother.Has achieve Front and rear maintenance.Rental Stage Indoor LED Screen 3.91 Video Full Color Led Panel Display/Screen LED Panel"},
            {title:"",value:"Exquisite Craft The curve lock it adopts is very easy to operate,both concave and convex is available,the manufacturing is precise amd accurate"},
            {title:"Excellent Quality",value:"Our field-tested LED panel is a self-contained, modular unit made of die-casting aluminum to provide superior heat dissipation,durability, and a longer lifespan. Unlike most digital signs, ours have no fans. This unique product meets strict quality controland is backed by a three year warranty."},
        ],
        specsType:1,
        productSpecs: [
            {
                title:"",
                specs:[
                    { title: "Application", content: "Indoor" },
                    { title: "Color", content: "Full Color" },
                    { title: "Panel Size", content: "500*500mm" },
                    { title: "Pixel Pitch", content: "1.9/2.6/2.9/3.91/4.81mm" },
                    { title: "Place of Origin", content: "Guangdong, China" },
                    { title: "Model Number", content: "E3.9" },
                    { title: "Brand Name", content: "Tentech" },
                    { title: "Product Name", content: "P 3.91 Smd P2.976 P391 4.81 1.9Mm Smd2121 Display Wall" },
                    { title: "Cabinet size", content: "500*500*64mm" },
                    { title: "Cabinet weight", content: "6Kgs" },
                    { title: "Cabinet pixels (dots)", content: "128*128" },
                    { title: "Refresh Rate(Hz)", content: "≥1920" },
                    { title: "Driving Method", content: "1/16" },
                    { title: "Cabinet Material", content: "Die Casting Alunimum" },
                    { title: "Brightness", content: "1200nits" },
                    { title: "LED Chips", content: "SMD2121" }
                ]
            },
            {
                title: "OUTDOOR Item Parameter",
                specs:  [
                    { title: "Model Number", content: "P3.91-13S" },
                    { title: "Module size", content: "250mm*250mm" },
                    { title: "Pixel pitch", content: "3.91mm" },
                    { title: "Pixels Density", content: "65536/m2" },
                    { title: "Pixel configuration", content: "1R1G1B" },
                    { title: "Package mode", content: "SMD1921" },
                    { title: "Pixel resolution", content: "64dots(W)*64dots(H)" },
                    { title: "Max Power consumption", content: "60W" },
                    { title: "Weight", content: "1.2kg" },
                    { title: "Drive type", content: "Constant drive" },
                    { title: "Scan mode", content: "1/16scan" },
                    { title: "LED Unit Module", content: "" },
                    { title: "Quanty of Module", content: "4pcs/8pcs" },
                    { title: "Power supply", content: "5V/60A" },
                    { title: "Pixel per cabinet", content: "128*128/128*256" },
                    { title: "Brightness of white balance", content: "≥7500cd/m2" },
                    { title: "Best viewing distance", content: "4M~50M" },
                    { title: "Viewing angles", content: "160°(W) 120°(H)" },
                    { title: "Temperature storage", content: "-35℃~+85℃, working:-20℃~+50℃" },
                    { title: "Operation humidity", content: "10%-95%" },
                    { title: "Thickness", content: "85mm" },
                    { title: "Power Working voltage", content: "AC220V±10%" },
                    { title: "Average Power consumption", content: "600W/S" },
                    { title: "Max.Power consumption", content: "≤1800W/S" },
                    { title: "Current", content: "≤20mA(single LED)" },
                    { title: "Control system CPU", content: "Pentium 4 or above" },
                    { title: "Operation system", content: "WIN98/2000/NT/XP" },
                    { title: "Control method", content: "Synchronization" },
                    { title: "Main technical parameter", content: "" },
                    { title: "Driving device", content: "Constant currentdriver IC Refresh frequency: ≥400HZ" },
                    { title: "Grey scale/colors", content: "RGB256,16.7M 256levels of each color(RGB)/16.7M colors" },
                    { title: "MTBF", content: "≥9000hours" },
                    { title: "Power switch", content: "Automatic switch" },
                    { title: "Display Mode", content: "800*600/1024*768" },
                    { title: "Waterproof Rate", content: "IP65" }
                ],
            },
        ],
        warrentyTerms:{
            title:"Tentech provides an excellent after-sales service on the prerequisite of customer satisfaction.",
            terms:[
                {termsContent:"All the products owners purchased from TENTECH possess the following rights:",subTermsContent:[
                        {title:"A:Unconditional replacement within 7 days."},
                        {title:"B:2 years warranty for maintenance."},
                    ]},
                {termsContent:"The repaired products will be sent back at TENTECH cost to customer within 7 days( from the date we receive the defective products at customers cost).",subTermsContent:[]},
                {termsContent:"100% authentic strict assessment, for you to select high visibility, quality, good service goods; 10 times refund in case any fake were found.",subTermsContent:[]},
                {termsContent:"12 hours after-sale service TENTECH professional services team promises to resolve any problems related to the use, installation and configuration of the product within 12 hours.",subTermsContent:[]},
                {termsContent:" 30 days price protection If the price of the products as what you purchased is getting lower within 30 days, TENTECH will refund the price difference. ",subTermsContent:[]},
            ]
        },
        productBrochure:{title:"Product Brochure",downloadUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/outdoor-waterproof-391-led-display/outdoor-waterproof-391-led-display.pdf"},
        productMediaResources:[
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/outdoor-waterproof-391-led-display/outdoor-waterproof-391-led-display-01.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/outdoor-waterproof-391-led-display/outdoor-waterproof-391-led-display-02.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/outdoor-waterproof-391-led-display/outdoor-waterproof-391-led-display-03.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/outdoor-waterproof-391-led-display/outdoor-waterproof-391-led-display-04.jpg"},
        ],
        productTag:[
            {tagTitle:"500*500mm rental screen",value:"500%2A500mm+rental+screen"},
            {tagTitle:"Chinese LED display manufacturer rental led screen p391",value:"Chinese+LED+display+manufacturer+rental+led+screen+p391"},
            {tagTitle:"2021 new HD full color P391 Rental indoor 500 X 500 Led Display",value:"2021+new+HD+full+color+P391+Rental+indoor+500+X+500+Led+Display"},
        ]
    },
    {
        isHotSell:false,
        productName:"Outdoor 3.91 Rental Screen High Quality",
        productModel:"outdoor-391-rental-screen-high-quality",
        brand:"TENTECH",
        productOrigin:"CHINA",
        supplyCapacity:"100 SQM PER DAY",
        deliveryTime:"3-5DAYS",
        description:[
            {title:"",value:"Special Design This Panel has both 500*500mm and 500*1000mm verstion,and the two verstion can be used togother.Has achieve Front and rear maintenance.Rental Stage Indoor LED Screen 3.91 Video Full Color Led Panel Display/Screen LED Panel"},
            {title:"",value:"Exquisite Craft The curve lock it adopts is very easy to operate,both concave and convex is available,the manufacturing is precise amd accurate"},
            {title:"Excellent Quality",value:"Our field-tested LED panel is a self-contained, modular unit made of die-casting aluminum to provide superior heat dissipation,durability, and a longer lifespan. Unlike most digital signs, ours have no fans. This unique product meets strict quality controland is backed by a three year warranty."},
        ],
        specsType:1,
        productSpecs: [
            {
                title:"",
                specs:[
                    { title: "Application", content: "Indoor" },
                    { title: "Color", content: "Full Color" },
                    { title: "Panel Size", content: "500*500mm" },
                    { title: "Pixel Pitch", content: "1.9/2.6/2.9/3.91/4.81mm" },
                    { title: "Place of Origin", content: "Guangdong, China" },
                    { title: "Model Number", content: "E3.9" },
                    { title: "Brand Name", content: "Tentech" },
                    { title: "Product Name", content: "P 3.91 Smd P2.976 P391 4.81 1.9Mm Smd2121 Display Wall" },
                    { title: "Cabinet size", content: "500*500*64mm" },
                    { title: "Cabinet weight", content: "6Kgs" },
                    { title: "Cabinet pixels (dots)", content: "128*128" },
                    { title: "Refresh Rate(Hz)", content: "≥1920" },
                    { title: "Driving Method", content: "1/16" },
                    { title: "Cabinet Material", content: "Die Casting Alunimum" },
                    { title: "Brightness", content: "1200nits" },
                    { title: "LED Chips", content: "SMD2121" }
                ]
            },
            {
                title: "OUTDOOR Item Parameter",
                specs:  [
                    { title: "Model Number", content: "P3.91-13S" },
                    { title: "Module size", content: "250mm*250mm" },
                    { title: "Pixel pitch", content: "3.91mm" },
                    { title: "Pixels Density", content: "65536/m2" },
                    { title: "Pixel configuration", content: "1R1G1B" },
                    { title: "Package mode", content: "SMD1921" },
                    { title: "Pixel resolution", content: "64dots(W)*64dots(H)" },
                    { title: "Max Power consumption", content: "60W" },
                    { title: "Weight", content: "1.2kg" },
                    { title: "Drive type", content: "Constant drive" },
                    { title: "Scan mode", content: "1/16scan" },
                    { title: "LED Unit Module", content: "" },
                    { title: "Quanty of Module", content: "4pcs/8pcs" },
                    { title: "Power supply", content: "5V/60A" },
                    { title: "Pixel per cabinet", content: "128*128/128*256" },
                    { title: "Brightness of white balance", content: "≥7500cd/m2" },
                    { title: "Best viewing distance", content: "4M~50M" },
                    { title: "Viewing angles", content: "160°(W) 120°(H)" },
                    { title: "Temperature storage", content: "-35℃~+85℃, working:-20℃~+50℃" },
                    { title: "Operation humidity", content: "10%-95%" },
                    { title: "Thickness", content: "85mm" },
                    { title: "Power Working voltage", content: "AC220V±10%" },
                    { title: "Average Power consumption", content: "600W/S" },
                    { title: "Max.Power consumption", content: "≤1800W/S" },
                    { title: "Current", content: "≤20mA(single LED)" },
                    { title: "Control system CPU", content: "Pentium 4 or above" },
                    { title: "Operation system", content: "WIN98/2000/NT/XP" },
                    { title: "Control method", content: "Synchronization" },
                    { title: "Main technical parameter", content: "" },
                    { title: "Driving device", content: "Constant currentdriver IC Refresh frequency: ≥400HZ" },
                    { title: "Grey scale/colors", content: "RGB256,16.7M 256levels of each color(RGB)/16.7M colors" },
                    { title: "MTBF", content: "≥9000hours" },
                    { title: "Power switch", content: "Automatic switch" },
                    { title: "Display Mode", content: "800*600/1024*768" },
                    { title: "Waterproof Rate", content: "IP65" }
                ],
            },
        ],
        warrentyTerms:{
            title:"Tentech provides an excellent after-sales service on the prerequisite of customer satisfaction.",
            terms:[
                {termsContent:"All the products owners purchased from TENTECH possess the following rights:",subTermsContent:[
                        {title:"A:Unconditional replacement within 7 days."},
                        {title:"B:2 years warranty for maintenance."},
                    ]},
                {termsContent:"The repaired products will be sent back at TENTECH cost to customer within 7 days( from the date we receive the defective products at customers cost).",subTermsContent:[]},
                {termsContent:"100% authentic strict assessment, for you to select high visibility, quality, good service goods; 10 times refund in case any fake were found.",subTermsContent:[]},
                {termsContent:"12 hours after-sale service TENTECH professional services team promises to resolve any problems related to the use, installation and configuration of the product within 12 hours.",subTermsContent:[]},
                {termsContent:" 30 days price protection If the price of the products as what you purchased is getting lower within 30 days, TENTECH will refund the price difference. ",subTermsContent:[]},
            ]
        },
        productBrochure:{title:"Product Brochure",downloadUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/outdoor-391-rental-screen-high-quality/outdoor-391-rental-screen-high-quality.pdf"},
        productMediaResources:[
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/outdoor-391-rental-screen-high-quality/outdoor-391-rental-screen-high-quality-01.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/rental-led-display/outdoor-391-rental-screen-high-quality/outdoor-391-rental-screen-high-quality-02.jpg"},
        ],
        productTag:[
            {tagTitle:"outdoor 3.91 rental screen",value:"outdoor+391+rental+screen"},
            {tagTitle:"Full Color Rental Led Display Screen Waterproof Outdoor LED Rental Screen For Stage Background",value:"Full+Color+Rental+Led+Display+Screen+Waterproof+Outdoor+LED+Rental+Screen+For+Stage+Background"},
            {tagTitle:"P3.91 P4.81 Waterproof and Rainroof Advertising Display Rental Outdoor LED Screen",value:"P391+P481+Waterproof+and+Rainroof+Advertising+Display+Rental+Outdoor+LED+Screen"},
        ]
    },
    {
        isHotSell:false,
        productName:"Professional Led Display Panel Indoor Outdoor Screen",
        productModel:"professional-led-display-panel-indoor-outdoor-screen",
        brand:"TENTECH",
        productOrigin:"CHINA",
        supplyCapacity:"100 SQM PER DAY",
        deliveryTime:"3-5DAYS",
        description:[
            {title:"Environmental Advantages",value:""},
            {title: '',value:'1) Keep people safe.' },
            {title: '',value:'2) Improving the quality of life.' },
            {title: '',value:'3) Outdoor LED signs deliver better service' },
            {title:"Business Advantages",value:""},
            {title: '',value:'1) Boadening customer base.' },
            {title: '',value:'2) High-quality images.' },
            {title: '',value:'3) Release content efficiently' },
        ],
        specsType:2,
        productSpecs: [
            {
                title:"Pixel Pitch",
                specs:[
                    { title: "P5", content: "" },
                    { title: "P6.67", content: "" },
                    { title: "P8", content: "" },
                    { title: "P10", content: "" },

                ]
            },
            {
                title: "LED Configuration",
                specs:  [
                    { title: "SMD 3 IN 1 ", content: "" },
                    { title: "SMD 3 IN 1", content: "" },
                    { title: "SMD 3 IN 1", content: "" },
                    { title: "SMD 3 IN 1", content: "" },
                ],
            },
            {
                title: "Pixel Density",
                specs:  [
                    { title: "40000pixel/m2 ", content: "" },
                    { title: "22500pixel/m2", content: "" },
                    { title: "15625pixel/m2", content: "" },
                    { title: "10000pixel/m2", content: "" },
                ],
            },
            {
                title: "Module size",
                specs:  [
                    { title: "40000pixel/m2 ", content: "" },
                    { title: "22500pixel/m2", content: "" },
                    { title: "15625pixel/m2", content: "" },
                    { title: "10000pixel/m2", content: "" },
                ],
            },
            {
                title: "Module Resolution ",
                specs:  [
                    { title: "64*32 dots ", content: "" },
                    { title: "48*24dots", content: "" },
                    { title: "40*20 dots", content: "" },
                    { title: "32*16dots", content: "" },
                ],
            },
            {
                title: "Screen size",
                specs:  [
                    { title: "Customize", content: "" },
                    { title: "Customize", content: "" },
                    { title: "Customize", content: "" },
                    { title: "Customize", content: "" },
                ],
            },
            {
                title: "Cabinet Resolution",
                specs:  [
                    { title: "192*192 dots ", content: "" },
                    { title: "144*144dots", content: "" },
                    { title: "120*120dots", content: "" },
                    { title: "96*96dots", content: "" },
                ],
            },
            {
                title: "Cabinet Weight",
                specs:  [
                    { title: "13kg", content: "" },
                    { title: "13kg", content: "" },
                    { title: "13kg", content: "" },
                    { title: "13kg", content: "" },
                ],
            },
            {
                title: "Cabinet material ",
                specs:  [
                    { title: "Mag Alloy ", content: "" },
                    { title: "Mag Alloy ", content: "" },
                    { title: "Mag Alloy ", content: "" },
                    { title: "Mag Alloy ", content: "" },
                ],
            },
            {
                title: "IP Rating ",
                specs:  [
                    { title: "IP65", content: "" },
                    { title: "IP65", content: "" },
                    { title: "IP65", content: "" },
                    { title: "IP65", content: "" },
                ],
            },
            {
                title: "Installation ",
                specs:  [
                    { title: "Hanging and fixed", content: "" },
                    { title: "Hanging and fixed", content: "" },
                    { title: "Hanging and fixed", content: "" },
                    { title: "Hanging and fixed", content: "" },
                ],
            },
            {
                title: "Brightness  ",
                specs:  [
                    { title: "5000-5500nicts/m2", content: "" },
                    { title: "5000-5500nicts/m2", content: "" },
                    { title: "5000-5500nicts/m2", content: "" },
                    { title: "5000-5500nicts/m2", content: "" },
                ],
            },
            {
                title: "Driving Mode   ",
                specs:  [
                    { title: "1/8scan", content: "" },
                    { title: "1/6scan ", content: "" },
                    { title: "1/5scan", content: "" },
                    { title: "1/4scan or 1/2scan", content: "" },
                ],
            },
            {
                title: "Display scale",
                specs:  [
                    { title: "16.7M", content: "" },
                    { title: "16.7M", content: "" },
                    { title: "16.7M", content: "" },
                    { title: "16.7M", content: "" },
                ],
            },
            {
                title: "Refresh Frequency",
                specs:  [
                    { title: "1920Hz", content: "" },
                    { title: "1920Hz", content: "" },
                    { title: "1920Hz", content: "" },
                    { title: "1920Hz", content: "" },
                ],
            },
            {
                title: "Operating Power ",
                specs:  [
                    { title: "AC96~242v", content: "" },
                    { title: "AC96~242v", content: "" },
                    { title: "AC96~242v", content: "" },
                    { title: "AC96~242v", content: "" },
                ],
            },
            {
                title: "Operating Life  ",
                specs:  [
                    { title: "100,000Hours", content: "" },
                    { title: "100,000Hours", content: "" },
                    { title: "100,000Hours", content: "" },
                    { title: "100,000Hours", content: "" },
                ],
            },
        ],
        warrentyTerms:{
            title:"Tentech provides an excellent after-sales service on the prerequisite of customer satisfaction.",
            terms:[
                {termsContent:"All the products owners purchased from TENTECH possess the following rights:",subTermsContent:[
                        {title:"A:Unconditional replacement within 7 days."},
                        {title:"B:2 years warranty for maintenance."},
                    ]},
                {termsContent:"The repaired products will be sent back at TENTECH cost to customer within 7 days( from the date we receive the defective products at customers cost).",subTermsContent:[]},
                {termsContent:"100% authentic strict assessment, for you to select high visibility, quality, good service goods; 10 times refund in case any fake were found.",subTermsContent:[]},
                {termsContent:"12 hours after-sale service TENTECH professional services team promises to resolve any problems related to the use, installation and configuration of the product within 12 hours.",subTermsContent:[]},
                {termsContent:" 30 days price protection If the price of the products as what you purchased is getting lower within 30 days, TENTECH will refund the price difference. ",subTermsContent:[]},
            ]
        },
        productBrochure:{title:"Product Brochure",downloadUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/fixed-install-led-display/professional-led-display-panel-indoor-outdoor-screen/professional-led-display-panel-indoor-outdoor-screen.pdf"},
        productMediaResources:[
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/fixed-install-led-display/professional-led-display-panel-indoor-outdoor-screen/professional-led-display-panel-indoor-outdoor-screen-01.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/fixed-install-led-display/professional-led-display-panel-indoor-outdoor-screen/professional-led-display-panel-indoor-outdoor-screen-02.jpg"},
            {title:"",type:"img",ResourcesUrl:"https://tentech.oss-cn-shenzhen.aliyuncs.com/images/products/fixed-install-led-display/professional-led-display-panel-indoor-outdoor-screen/professional-led-display-panel-indoor-outdoor-screen-03.jpg"},
        ],
        productTag:[
            {tagTitle:"waterproof led screen",value:"waterproof+led+screen"},
            {tagTitle:"P3.91 Outdoor LED Screen for advertising and rental",value:"P391+Outdoor+LED+Screen+for+advertising+and+rental"},
            {tagTitle:"P3.91 Rental Outdoor Led Display",value:"P391+Rental+Outdoor+Led+Display"},
            {tagTitle:"Waterproof Giant P3 Stage Led Video Wall Panel Screen",value:"Waterproof+Giant+P3+Stage+Led+Video+Wall+Panel+Screen"},
        ]
    },
]