const productDirectoryMenuList = [
    {
        router:"/rental-led-display",
        name:"Rental LED Display",
        isHover:false,
        isSelected:false,
        desc:"租赁显示屏",
        subMenuVisible: false,
        subMenus:[],
    },
    {
        router:"/fixed-install-led-display",
        name:"Fixed Install Led Display",
        isHover:false,
        isSelected:false,
        subMenuVisible: false,
        desc:"固定安装LED显示屏",
        subMenus:[
            {router:"/led-cube-screen",name:"led-cube-screen",path:"/product-list",seriesId:3,isHover:false,isSelected:false,desc:"立方体屏幕",},
        ]},
    {
        router:"fines-mall-pixel-led-display",
        name:"Fine/small Pixel Led Display",
        path:'/series',
        seriesId:1,
        isHover:false,
        isSelected:false,
        desc:"精细/小像素LED显示屏",
        subMenuVisible: false,
        subMenus:[],
    },
    {
        router:"transparent-led-display",
        name:"Transparent LED Display",
        path:'/series',
        seriesId:2,
        isHover:false,
        isSelected:false,
        desc:"透明LED显示屏",
        subMenuVisible: false,
        subMenus:[],
    },
    {
        router:"iposter",
        name:"Iposter LED Display",
        path:'/series',
        seriesId:5,
        isHover:false,
        isSelected:false,
        desc:"海报LED显示屏",
        subMenuVisible: false,
        subMenus:[],
    },
    {
        router:"creative-display",
        name:"Creative Display",
        path:'/series',
        seriesId:6,
        isHover:false,
        isSelected:false,
        desc:"创意LED显示屏",
        subMenuVisible: false,
        subMenus:[],
    },
    {
        router:"led-module",
        name:"LED Module",
        path:'/series',
        seriesId:7,
        isHover:false,
        isSelected:false,
        desc:"LED模块",
        subMenuVisible: false,
        subMenus:[],
    },
    {
        router:"led-display-accessories",
        name:"LED Display Accessories",
        path:'/series',
        seriesId:7,
        isHover:false,
        isSelected:false,
        desc:"显示屏配件",
        subMenuVisible: false,
        subMenus:[],
    },
]

export default {
    productDirectoryMenuList
}